### ISSUE TITLE
Inconsistent type argument order

### ISSUE THREAD

**Issue by Mikolaj** [augustss/orthotope#11]
These two take their type argument (the "shape" and the payload type) in different order:

https://hackage.haskell.org/package/orthotope-0.1.2.0/docs/Data-Array-RankedS.html#v:fromList

https://hackage.haskell.org/package/orthotope-0.1.2.0/docs/Data-Array-ShapedS.html#v:fromList

I'm fine with either of these and I will standardise in horde-ad on the one chosen in orthotope. The chosen order is not a big deal thanks to the `@_` idiom that permits skipping type arguments when applying, but having to remember which operation uses which order is problematic and it obfuscates error messages.

**Comment by Mikolaj** [comment]
Actually, I think I opt for providing the shape first, since it changes more often than the type of elements of the tensors, as a rule.

**Comment by augustss** [comment]
Fixed in b404b6922dc11edb8a16af61af20b1e3e5b7cc70

**Comment by Mikolaj** [comment]
Thank you! :)
