### ISSUE TITLE
Memory leak in RankedS.scalar

### ISSUE THREAD

**Issue by Mikolaj** [augustss/orthotope#8]
I'm seeing thunks created in function 

https://hackage.haskell.org/package/orthotope-0.1.2.0/docs/src/Data.Array.Internal.RankedS.html#scalar

most probably due to 

https://hackage.haskell.org/package/orthotope-0.1.2.0/docs/src/Data.Array.Internal.RankedG.html#Array

not having strict fields. For context, note how the following has some strict fields:

https://hackage.haskell.org/package/orthotope-0.1.2.0/docs/src/Data.Array.Internal.html#T

Shall we make both or the second field of `data Array (n :: Nat) v a = A ShapeL (T v a)` strict? I'm seeing

   Data/Array/Internal/DynamicG.hs:data Array v a = A !ShapeL !(T v a)

so probably the policy is that shapes are strict and strides are lazy, which seems to match my use case very well.

How about declaring a global `StrictData` extension in the data file and mark (with `~`) only the fields that should not be strict?

I'm ready to prepare a PR, but it's easy to make a design mistake here, so I can't start before brainstorming.

**Comment by augustss** [comment]
Actually, I'll fix it.

**Comment by Mikolaj** [comment]
Looks good. Thank you.

**Comment by Mikolaj** [comment]
Originally my big benchmark (with a lot going on, orthotope only taking a fraction of time, but plausibly retaining some other objects) had

```
 286,527,395,824 bytes allocated in the heap
 145,765,844,480 bytes copied during GC
  14,236,709,792 bytes maximum residency (12 sample(s))
     259,297,136 bytes maximum slop
           32401 MiB total memory in use (0 MiB lost due to fragmentation)

                                     Tot time (elapsed)  Avg pause  Max pause
  Gen  0       342 colls,     0 par   64.599s  64.625s     0.1890s    0.9978s
  Gen  1        12 colls,     0 par   47.509s  47.541s     3.9618s    10.5449s

  INIT    time    0.008s  (  0.008s elapsed)
  MUT     time   47.707s  ( 47.658s elapsed)
  GC      time  112.108s  (112.166s elapsed)
  EXIT    time    0.000s  (  0.000s elapsed)
  Total   time  159.823s  (159.832s elapsed)

  %GC     time       0.0%  (0.0% elapsed)

  Alloc rate    6,005,934,858 bytes per MUT second

  Productivity  29.9% of total user, 29.8% of total elapsed
```

after the changes up to but not including strict strides I get

```
 285,138,773,464 bytes allocated in the heap
 162,042,352,512 bytes copied during GC
  15,327,638,648 bytes maximum residency (22 sample(s))
     427,867,320 bytes maximum slop
           38255 MiB total memory in use (0 MiB lost due to fragmentation)

                                     Tot time (elapsed)  Avg pause  Max pause
  Gen  0     67579 colls,     0 par   45.189s  45.251s     0.0007s    0.0652s
  Gen  1        22 colls,     0 par   52.784s  52.831s     2.4014s    11.5789s

  INIT    time    0.000s  (  0.000s elapsed)
  MUT     time   44.984s  ( 44.947s elapsed)
  GC      time   97.974s  ( 98.083s elapsed)
  EXIT    time    0.000s  (  0.000s elapsed)
  Total   time  142.958s  (143.030s elapsed)

  %GC     time       0.0%  (0.0% elapsed)

  Alloc rate    6,338,656,962 bytes per MUT second

  Productivity  31.5% of total user, 31.4% of total elapsed
```

Let me now benchmark with strict strides.

**Comment by augustss** [comment]
The strides really should be a list of strict Int.  Like
  data IntList = Nil | Cons {-# UNBOX #-}Int IntList
and the offset should be unboxed as well.
The former change is a lot of work, since strides are used with a lot of
list functions.
Unboxing the offset should be trivial.

**Comment by Mikolaj** [comment]
> Unboxing the offset should be trivial.

I guess it's already unboxed while residing in the record:

https://downloads.haskell.org/ghc/latest/docs/users_guide/using-optimisation.html?highlight=unbox#ghc-flag--funbox-small-strict-fields

> The former change is a lot of work, since strides are used with a lot of list functions.

We have package(s) for that now, though I haven't used them yet, e.g., https://hackage.haskell.org/package/strict-list

For the record, with strict strides the benchmark yields the following, so basically no change vs lazy strides (while the other strictness changes sped up the benchmark a lot, as seen above, though there is allocation noise probably from other memory leaks I haven't tackled yet):
```
 285,138,773,464 bytes allocated in the heap
 162,042,352,232 bytes copied during GC
  15,327,638,648 bytes maximum residency (22 sample(s))
     427,867,344 bytes maximum slop
           38255 MiB total memory in use (0 MiB lost due to fragmentation)

                                     Tot time (elapsed)  Avg pause  Max pause
  Gen  0     67579 colls,     0 par   45.795s  45.877s     0.0007s    0.0648s
  Gen  1        22 colls,     0 par   52.874s  52.939s     2.4063s    11.5540s

  INIT    time    0.000s  (  0.000s elapsed)
  MUT     time   45.012s  ( 44.966s elapsed)
  GC      time   98.669s  ( 98.816s elapsed)
  EXIT    time    0.000s  (  0.000s elapsed)
  Total   time  143.682s  (143.782s elapsed)

  %GC     time       0.0%  (0.0% elapsed)

  Alloc rate    6,334,721,381 bytes per MUT second

  Productivity  31.3% of total user, 31.3% of total elapsed
```

**Comment by Mikolaj** [comment]
> I don't think the strictlist package will automatically unbox the strict Int.

I think you are right --- we'd probably need backpack to unpack a strict field which holds a type variable, as in `data List a = Cons !a !(List a) | Nil`, a custom datatype may be sadly the only option.

**Comment by augustss** [comment]
I've fixed some bugs in the pretty printing and updated the documentation a
little bit.

**Comment by Mikolaj** [comment]
Therefore, let me close it. Thank you again.
